packages:
  - sub_projects/**
  - '!sub_projects/node-library'
  - examples/desktop-app
  - '!**/test/**'
# ignoredBuiltDependencies:
  # - '@parcel/watcher'
  # - better-sqlite3
onlyBuiltDependencies:
  - core-js
  - electron
  - esbuild
  - lzma-native
  - vue-demi
